apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  namespace: guestbook-ui
  annotations:
    argocd-image-updater.argoproj.io/image-list: "peamsam/nginx"
    argocd-image-updater.argoproj.io/peamsam/nginx.update-strategy: "latest"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: peamsam/nginx:develop
        name: guestbook-ui
        ports:
        - containerPort: 80
